CREATE TABLE STAGE_ATENDIMENTO (
    ID                      NUMBER(19),
    TICKET_ID               NUMBER(19),
    HISTORY_TYPE_ID         NUMBER(5),
    CREATE_TIME             TIMESTAMP,
    OWNER_ID                VARCHAR2(200),
    CHANGE_BY               NUMBER(10),
    QUEUE_ID                NUMBER(10),
    STATUS_ID               NUMBER(5),
    TYPE_ID                 NUMBER(10),
    DATA_INCLUSAO           TIMESTAMP ,
    ULTIMA_DATA_ALTERACAO   TIMESTAMP DEFAULT SYSTIMESTAMP
)
SEGMENT CREATION DEFERRED
PARALLEL
COMPRESS BASIC;

CREATE INDEX IDX_STAGE_ATENDIMENTO
ON STAGE_ATENDIMENTO (
    TICKET_ID,
    OWNER_ID,
    CHANGE_BY,
    QUEUE_ID,
    STATUS_ID,
    TYPE_ID,
    CREATE_TIME
);

