CREATE GLOBAL TEMPORARY TABLE TMP_FATO_GRUPOS (
    TICKET_ID      NUMBER(19),
    HISTORY_TYPE_ID NUMBER(5),
    CREATE_TIME    TIMESTAMP,
    OWNER_ID       NUMBER(10),
    CHANGE_BY      NUMBER(10),
    QUEUE_ID       NUMBER(10),
    STATUS_ID       NUMBER(5),
    TYPE_ID        NUMBER(5),
    PREV_OWNER     NUMBER,
    PREV_ATTENDENT NUMBER,
    PREV_QUEUE     NUMBER,
    PREV_STATUS    NUMBER,
    PREV_TYPE      NUMBER,
    ORDEM_TICKET   NUMBER,
    DATA_INCLUSAO TIMESTAMP,
    MUDOU          NUMBER(1),
    GRUPO          NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE TMP_FATO_MARCACOES (
    TICKET_ID      NUMBER(19),
    HISTORY_TYPE_ID NUMBER(5),
    CREATE_TIME    TIMESTAMP,
    OWNER_ID       NUMBER(10),
    CHANGE_BY      NUMBER(10),
    QUEUE_ID       NUMBER(10),
    STATUS_ID       NUMBER(5),
    TYPE_ID        NUMBER(5),
    PREV_OWNER     NUMBER,
    PREV_ATTENDENT NUMBER,
    PREV_QUEUE     NUMBER,
    PREV_STATUS    NUMBER,
    PREV_TYPE      NUMBER,
    ORDEM_TICKET   NUMBER,
    DATA_INCLUSAO TIMESTAMP,
    MUDOU          NUMBER(1)
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_FATO_LAGS (
    TICKET_ID      NUMBER(19),
    HISTORY_TYPE_ID NUMBER(5),
    CREATE_TIME    TIMESTAMP,
    OWNER_ID       NUMBER(10),
    CHANGE_BY      NUMBER(10),
    QUEUE_ID       NUMBER(10),
    STATUS_ID       NUMBER(5),
    TYPE_ID        NUMBER(5),
    PREV_OWNER     NUMBER,
    PREV_ATTENDENT NUMBER,
    PREV_QUEUE     NUMBER,
    PREV_STATUS    NUMBER,
    PREV_TYPE      NUMBER,
    ORDEM_TICKET   NUMBER,
    DATA_INCLUSAO TIMESTAMP
) ON COMMIT PRESERVE ROWS;

